{{- if .Values.server.autoscaling.enabled }}
apiVersion: {{ include "helm-k8s.autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "helm-k8s.labels" (dict "context" . "component" .Values.server.name "name" (printf "%s-hpa" .Values.server.name)) | nindent 4 }}
  name: {{ template "helm-k8s.server.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "helm-k8s.server.fullname" . }}
  minReplicas: {{ .Values.server.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  metrics:
{{- with .Values.server.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if eq (include "helm-k8s.autoscaling.apiVersion" $) "autoscaling/v2beta1" }}
        targetAverageUtilization: {{ . }}
        {{- else }}
        target:
          averageUtilization: {{ . }}
          type: Utilization
        {{- end }}
{{- end }}
{{- with .Values.server.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if eq (include "helm-k8s.autoscaling.apiVersion" $) "autoscaling/v2beta1" }}
        targetAverageUtilization: {{ . }}
        {{- else }}
        target:
          averageUtilization: {{ . }}
          type: Utilization
        {{- end }}
{{- end }}
{{- end }}